// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compression_ext.sql

package store

import (
	"context"
)

type BatchInsertCompressedObservationsParams struct {
	ID             string
	ObservationIds []string
	SessionID      string
	CompressedText string
	Concepts       []string
	OwnerType      string
	OwnerUserID    *string
	Visibility     string
}

const markObservationsCompressed = `-- name: MarkObservationsCompressed :exec
UPDATE observations SET compressed_at = NOW() WHERE id = ANY($1::text[])
`

func (q *Queries) MarkObservationsCompressed(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, markObservationsCompressed, dollar_1)
	return err
}
