// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compressed.sql

package store

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const deleteCompressedObservation = `-- name: DeleteCompressedObservation :exec
DELETE FROM compressed_observations WHERE id = $1
`

func (q *Queries) DeleteCompressedObservation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCompressedObservation, id)
	return err
}

const getCompressedEmbedding = `-- name: GetCompressedEmbedding :one
SELECT compressed_id, embedding, model, created_at FROM compressed_embeddings WHERE compressed_id = $1
`

func (q *Queries) GetCompressedEmbedding(ctx context.Context, compressedID string) (CompressedEmbedding, error) {
	row := q.db.QueryRow(ctx, getCompressedEmbedding, compressedID)
	var i CompressedEmbedding
	err := row.Scan(
		&i.CompressedID,
		&i.Embedding,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getCompressedObservation = `-- name: GetCompressedObservation :one
SELECT id, observation_ids, session_id, visibility, compressed_text, concepts, created_at FROM compressed_observations WHERE id = $1
`

func (q *Queries) GetCompressedObservation(ctx context.Context, id string) (CompressedObservation, error) {
	row := q.db.QueryRow(ctx, getCompressedObservation, id)
	var i CompressedObservation
	err := row.Scan(
		&i.ID,
		&i.ObservationIds,
		&i.SessionID,
		&i.Visibility,
		&i.CompressedText,
		&i.Concepts,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompressedEmbedding = `-- name: InsertCompressedEmbedding :exec
INSERT INTO compressed_embeddings (compressed_id, embedding, model)
VALUES ($1, $2, $3)
`

type InsertCompressedEmbeddingParams struct {
	CompressedID string
	Embedding    *pgvector.Vector
	Model        string
}

func (q *Queries) InsertCompressedEmbedding(ctx context.Context, arg InsertCompressedEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertCompressedEmbedding, arg.CompressedID, arg.Embedding, arg.Model)
	return err
}

const insertCompressedObservation = `-- name: InsertCompressedObservation :one
INSERT INTO compressed_observations (id, observation_ids, session_id, visibility, compressed_text, concepts)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, observation_ids, session_id, visibility, compressed_text, concepts, created_at
`

type InsertCompressedObservationParams struct {
	ID             string
	ObservationIds []string
	SessionID      string
	Visibility     string
	CompressedText string
	Concepts       []string
}

func (q *Queries) InsertCompressedObservation(ctx context.Context, arg InsertCompressedObservationParams) (CompressedObservation, error) {
	row := q.db.QueryRow(ctx, insertCompressedObservation,
		arg.ID,
		arg.ObservationIds,
		arg.SessionID,
		arg.Visibility,
		arg.CompressedText,
		arg.Concepts,
	)
	var i CompressedObservation
	err := row.Scan(
		&i.ID,
		&i.ObservationIds,
		&i.SessionID,
		&i.Visibility,
		&i.CompressedText,
		&i.Concepts,
		&i.CreatedAt,
	)
	return i, err
}

const listCompressedBySession = `-- name: ListCompressedBySession :many
SELECT id, observation_ids, session_id, visibility, compressed_text, concepts, created_at FROM compressed_observations WHERE session_id = $1 ORDER BY created_at
`

func (q *Queries) ListCompressedBySession(ctx context.Context, sessionID string) ([]CompressedObservation, error) {
	rows, err := q.db.Query(ctx, listCompressedBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompressedObservation
	for rows.Next() {
		var i CompressedObservation
		if err := rows.Scan(
			&i.ID,
			&i.ObservationIds,
			&i.SessionID,
			&i.Visibility,
			&i.CompressedText,
			&i.Concepts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
