// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForBatchInsertCompressedObservations implements pgx.CopyFromSource.
type iteratorForBatchInsertCompressedObservations struct {
	rows                 []BatchInsertCompressedObservationsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertCompressedObservations) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertCompressedObservations) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ObservationIds,
		r.rows[0].SessionID,
		r.rows[0].CompressedText,
		r.rows[0].Concepts,
		r.rows[0].OwnerType,
		r.rows[0].OwnerUserID,
		r.rows[0].Visibility,
	}, nil
}

func (r iteratorForBatchInsertCompressedObservations) Err() error {
	return nil
}

func (q *Queries) BatchInsertCompressedObservations(ctx context.Context, arg []BatchInsertCompressedObservationsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"compressed_observations"}, []string{"id", "observation_ids", "session_id", "compressed_text", "concepts", "owner_type", "owner_user_id", "visibility"}, &iteratorForBatchInsertCompressedObservations{rows: arg})
}

// iteratorForBatchInsertLessons implements pgx.CopyFromSource.
type iteratorForBatchInsertLessons struct {
	rows                 []BatchInsertLessonsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertLessons) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertLessons) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TeamID,
		r.rows[0].Visibility,
		r.rows[0].Content,
		r.rows[0].Context,
		r.rows[0].Confidence,
		r.rows[0].Source,
	}, nil
}

func (r iteratorForBatchInsertLessons) Err() error {
	return nil
}

func (q *Queries) BatchInsertLessons(ctx context.Context, arg []BatchInsertLessonsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lessons"}, []string{"id", "team_id", "visibility", "content", "context", "confidence", "source"}, &iteratorForBatchInsertLessons{rows: arg})
}

// iteratorForBatchInsertMemories implements pgx.CopyFromSource.
type iteratorForBatchInsertMemories struct {
	rows                 []BatchInsertMemoriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertMemories) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertMemories) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].OwnerType,
		r.rows[0].OwnerUserID,
		r.rows[0].OwnerTeamID,
		r.rows[0].Visibility,
		r.rows[0].Content,
		r.rows[0].Concepts,
		r.rows[0].Source,
		r.rows[0].Confidence,
	}, nil
}

func (r iteratorForBatchInsertMemories) Err() error {
	return nil
}

func (q *Queries) BatchInsertMemories(ctx context.Context, arg []BatchInsertMemoriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"memories"}, []string{"id", "owner_type", "owner_user_id", "owner_team_id", "visibility", "content", "concepts", "source", "confidence"}, &iteratorForBatchInsertMemories{rows: arg})
}
