// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package store

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const deleteEmbedding = `-- name: DeleteEmbedding :exec
DELETE FROM observation_embeddings WHERE observation_id = $1
`

func (q *Queries) DeleteEmbedding(ctx context.Context, observationID string) error {
	_, err := q.db.Exec(ctx, deleteEmbedding, observationID)
	return err
}

const getEmbedding = `-- name: GetEmbedding :one
SELECT observation_id, embedding, model, created_at FROM observation_embeddings WHERE observation_id = $1
`

func (q *Queries) GetEmbedding(ctx context.Context, observationID string) (ObservationEmbedding, error) {
	row := q.db.QueryRow(ctx, getEmbedding, observationID)
	var i ObservationEmbedding
	err := row.Scan(
		&i.ObservationID,
		&i.Embedding,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmbedding = `-- name: InsertEmbedding :exec
INSERT INTO observation_embeddings (observation_id, embedding, model)
VALUES ($1, $2, $3)
`

type InsertEmbeddingParams struct {
	ObservationID string
	Embedding     *pgvector.Vector
	Model         string
}

func (q *Queries) InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertEmbedding, arg.ObservationID, arg.Embedding, arg.Model)
	return err
}
