// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph_nodes.sql

package store

import (
	"context"
)

const deleteGraphNode = `-- name: DeleteGraphNode :exec
DELETE FROM graph_nodes WHERE id = $1
`

func (q *Queries) DeleteGraphNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGraphNode, id)
	return err
}

const getGraphNode = `-- name: GetGraphNode :one
SELECT id, node_type, entity_id, label, metadata, created_at, source_obs_ids FROM graph_nodes WHERE id = $1
`

func (q *Queries) GetGraphNode(ctx context.Context, id string) (GraphNode, error) {
	row := q.db.QueryRow(ctx, getGraphNode, id)
	var i GraphNode
	err := row.Scan(
		&i.ID,
		&i.NodeType,
		&i.EntityID,
		&i.Label,
		&i.Metadata,
		&i.CreatedAt,
		&i.SourceObsIds,
	)
	return i, err
}

const insertGraphNode = `-- name: InsertGraphNode :one
INSERT INTO graph_nodes (id, node_type, entity_id, label, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, node_type, entity_id, label, metadata, created_at, source_obs_ids
`

type InsertGraphNodeParams struct {
	ID       string
	NodeType string
	EntityID string
	Label    string
	Metadata []byte
}

func (q *Queries) InsertGraphNode(ctx context.Context, arg InsertGraphNodeParams) (GraphNode, error) {
	row := q.db.QueryRow(ctx, insertGraphNode,
		arg.ID,
		arg.NodeType,
		arg.EntityID,
		arg.Label,
		arg.Metadata,
	)
	var i GraphNode
	err := row.Scan(
		&i.ID,
		&i.NodeType,
		&i.EntityID,
		&i.Label,
		&i.Metadata,
		&i.CreatedAt,
		&i.SourceObsIds,
	)
	return i, err
}

const listGraphNodesByEntity = `-- name: ListGraphNodesByEntity :many
SELECT id, node_type, entity_id, label, metadata, created_at, source_obs_ids FROM graph_nodes WHERE entity_id = $1
`

func (q *Queries) ListGraphNodesByEntity(ctx context.Context, entityID string) ([]GraphNode, error) {
	rows, err := q.db.Query(ctx, listGraphNodesByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphNode
	for rows.Next() {
		var i GraphNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeType,
			&i.EntityID,
			&i.Label,
			&i.Metadata,
			&i.CreatedAt,
			&i.SourceObsIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphNodesByType = `-- name: ListGraphNodesByType :many
SELECT id, node_type, entity_id, label, metadata, created_at, source_obs_ids FROM graph_nodes WHERE node_type = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGraphNodesByType(ctx context.Context, nodeType string) ([]GraphNode, error) {
	rows, err := q.db.Query(ctx, listGraphNodesByType, nodeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphNode
	for rows.Next() {
		var i GraphNode
		if err := rows.Scan(
			&i.ID,
			&i.NodeType,
			&i.EntityID,
			&i.Label,
			&i.Metadata,
			&i.CreatedAt,
			&i.SourceObsIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGraphNode = `-- name: UpsertGraphNode :one
INSERT INTO graph_nodes (id, node_type, entity_id, label, metadata, source_obs_ids)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (label, node_type) DO UPDATE SET
    source_obs_ids = graph_nodes.source_obs_ids || EXCLUDED.source_obs_ids,
    metadata = EXCLUDED.metadata
RETURNING id, node_type, entity_id, label, metadata, created_at, source_obs_ids
`

type UpsertGraphNodeParams struct {
	ID           string
	NodeType     string
	EntityID     string
	Label        string
	Metadata     []byte
	SourceObsIds []string
}

func (q *Queries) UpsertGraphNode(ctx context.Context, arg UpsertGraphNodeParams) (GraphNode, error) {
	row := q.db.QueryRow(ctx, upsertGraphNode,
		arg.ID,
		arg.NodeType,
		arg.EntityID,
		arg.Label,
		arg.Metadata,
		arg.SourceObsIds,
	)
	var i GraphNode
	err := row.Scan(
		&i.ID,
		&i.NodeType,
		&i.EntityID,
		&i.Label,
		&i.Metadata,
		&i.CreatedAt,
		&i.SourceObsIds,
	)
	return i, err
}
