// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph_edges.sql

package store

import (
	"context"
)

const deleteGraphEdge = `-- name: DeleteGraphEdge :exec
DELETE FROM graph_edges WHERE id = $1
`

func (q *Queries) DeleteGraphEdge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGraphEdge, id)
	return err
}

const getGraphEdge = `-- name: GetGraphEdge :one
SELECT id, from_node_id, to_node_id, edge_type, weight, created_at, source_obs_ids FROM graph_edges WHERE id = $1
`

func (q *Queries) GetGraphEdge(ctx context.Context, id string) (GraphEdge, error) {
	row := q.db.QueryRow(ctx, getGraphEdge, id)
	var i GraphEdge
	err := row.Scan(
		&i.ID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.Weight,
		&i.CreatedAt,
		&i.SourceObsIds,
	)
	return i, err
}

const insertGraphEdge = `-- name: InsertGraphEdge :one
INSERT INTO graph_edges (id, from_node_id, to_node_id, edge_type, weight)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, from_node_id, to_node_id, edge_type, weight, created_at, source_obs_ids
`

type InsertGraphEdgeParams struct {
	ID         string
	FromNodeID string
	ToNodeID   string
	EdgeType   string
	Weight     float64
}

func (q *Queries) InsertGraphEdge(ctx context.Context, arg InsertGraphEdgeParams) (GraphEdge, error) {
	row := q.db.QueryRow(ctx, insertGraphEdge,
		arg.ID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.EdgeType,
		arg.Weight,
	)
	var i GraphEdge
	err := row.Scan(
		&i.ID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.Weight,
		&i.CreatedAt,
		&i.SourceObsIds,
	)
	return i, err
}

const listGraphEdgesFrom = `-- name: ListGraphEdgesFrom :many
SELECT id, from_node_id, to_node_id, edge_type, weight, created_at, source_obs_ids FROM graph_edges WHERE from_node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGraphEdgesFrom(ctx context.Context, fromNodeID string) ([]GraphEdge, error) {
	rows, err := q.db.Query(ctx, listGraphEdgesFrom, fromNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphEdge
	for rows.Next() {
		var i GraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.Weight,
			&i.CreatedAt,
			&i.SourceObsIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphEdgesTo = `-- name: ListGraphEdgesTo :many
SELECT id, from_node_id, to_node_id, edge_type, weight, created_at, source_obs_ids FROM graph_edges WHERE to_node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGraphEdgesTo(ctx context.Context, toNodeID string) ([]GraphEdge, error) {
	rows, err := q.db.Query(ctx, listGraphEdgesTo, toNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphEdge
	for rows.Next() {
		var i GraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.Weight,
			&i.CreatedAt,
			&i.SourceObsIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGraphEdge = `-- name: UpsertGraphEdge :one
INSERT INTO graph_edges (id, from_node_id, to_node_id, edge_type, weight, source_obs_ids)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (from_node_id, to_node_id, edge_type) DO UPDATE SET
    weight = (graph_edges.weight + EXCLUDED.weight) / 2.0,
    source_obs_ids = graph_edges.source_obs_ids || EXCLUDED.source_obs_ids
RETURNING id, from_node_id, to_node_id, edge_type, weight, created_at, source_obs_ids
`

type UpsertGraphEdgeParams struct {
	ID           string
	FromNodeID   string
	ToNodeID     string
	EdgeType     string
	Weight       float64
	SourceObsIds []string
}

func (q *Queries) UpsertGraphEdge(ctx context.Context, arg UpsertGraphEdgeParams) (GraphEdge, error) {
	row := q.db.QueryRow(ctx, upsertGraphEdge,
		arg.ID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.EdgeType,
		arg.Weight,
		arg.SourceObsIds,
	)
	var i GraphEdge
	err := row.Scan(
		&i.ID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.Weight,
		&i.CreatedAt,
		&i.SourceObsIds,
	)
	return i, err
}
