// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package store

import (
	"context"
)

const insertInsight = `-- name: InsertInsight :exec
INSERT INTO insights (id, content, confidence, source, created_at)
VALUES ($1, $2, $3, 'reflect', now())
`

type InsertInsightParams struct {
	ID         string
	Content    string
	Confidence float64
}

func (q *Queries) InsertInsight(ctx context.Context, arg InsertInsightParams) error {
	_, err := q.db.Exec(ctx, insertInsight, arg.ID, arg.Content, arg.Confidence)
	return err
}
