// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons_ext.sql

package store

type BatchInsertLessonsParams struct {
	ID         string
	TeamID     *string
	Visibility string
	Content    string
	Context    *string
	Confidence float64
	Source     string
}
