// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package store

import (
	"context"
)

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLesson, id)
	return err
}

const getLesson = `-- name: GetLesson :one
SELECT id, team_id, owner_user_id, visibility, content, context, confidence, source, created_at, last_reinforced_at FROM lessons WHERE id = $1
`

func (q *Queries) GetLesson(ctx context.Context, id string) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Visibility,
		&i.Content,
		&i.Context,
		&i.Confidence,
		&i.Source,
		&i.CreatedAt,
		&i.LastReinforcedAt,
	)
	return i, err
}

const insertLesson = `-- name: InsertLesson :one
INSERT INTO lessons (id, team_id, visibility, content, context, confidence, source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, team_id, owner_user_id, visibility, content, context, confidence, source, created_at, last_reinforced_at
`

type InsertLessonParams struct {
	ID         string
	TeamID     *string
	Visibility string
	Content    string
	Context    *string
	Confidence float64
	Source     string
}

func (q *Queries) InsertLesson(ctx context.Context, arg InsertLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, insertLesson,
		arg.ID,
		arg.TeamID,
		arg.Visibility,
		arg.Content,
		arg.Context,
		arg.Confidence,
		arg.Source,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Visibility,
		&i.Content,
		&i.Context,
		&i.Confidence,
		&i.Source,
		&i.CreatedAt,
		&i.LastReinforcedAt,
	)
	return i, err
}

const insertLessonReinforcement = `-- name: InsertLessonReinforcement :exec
INSERT INTO lesson_reinforcements (id, lesson_id, observation_id, confidence_delta)
VALUES ($1, $2, $3, $4)
`

type InsertLessonReinforcementParams struct {
	ID              string
	LessonID        string
	ObservationID   *string
	ConfidenceDelta float64
}

func (q *Queries) InsertLessonReinforcement(ctx context.Context, arg InsertLessonReinforcementParams) error {
	_, err := q.db.Exec(ctx, insertLessonReinforcement,
		arg.ID,
		arg.LessonID,
		arg.ObservationID,
		arg.ConfidenceDelta,
	)
	return err
}

const listAllLessons = `-- name: ListAllLessons :many
SELECT id, team_id, owner_user_id, visibility, content, context, confidence, source, created_at, last_reinforced_at FROM lessons
WHERE ($2::text IS NULL OR team_id = $2)
ORDER BY created_at DESC
LIMIT $1
`

type ListAllLessonsParams struct {
	Limit  int32
	TeamID *string
}

// sqlc.narg('team_id') enforces cross-tenant isolation.
func (q *Queries) ListAllLessons(ctx context.Context, arg ListAllLessonsParams) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listAllLessons, arg.Limit, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OwnerUserID,
			&i.Visibility,
			&i.Content,
			&i.Context,
			&i.Confidence,
			&i.Source,
			&i.CreatedAt,
			&i.LastReinforcedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByTeam = `-- name: ListLessonsByTeam :many
SELECT id, team_id, owner_user_id, visibility, content, context, confidence, source, created_at, last_reinforced_at FROM lessons WHERE team_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListLessonsByTeamParams struct {
	TeamID *string
	Limit  int32
}

func (q *Queries) ListLessonsByTeam(ctx context.Context, arg ListLessonsByTeamParams) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByTeam, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OwnerUserID,
			&i.Visibility,
			&i.Content,
			&i.Context,
			&i.Confidence,
			&i.Source,
			&i.CreatedAt,
			&i.LastReinforcedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfidence = `-- name: UpdateConfidence :exec
UPDATE lessons SET confidence = $2, last_reinforced_at = now() WHERE id = $1
`

type UpdateConfidenceParams struct {
	ID         string
	Confidence float64
}

func (q *Queries) UpdateConfidence(ctx context.Context, arg UpdateConfidenceParams) error {
	_, err := q.db.Exec(ctx, updateConfidence, arg.ID, arg.Confidence)
	return err
}
