// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories_search.sql

package store

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const bm25SearchMemories = `-- name: Bm25SearchMemories :many
SELECT m.id::text AS id, paradedb.score(m.id)::float8 AS bm25_score
FROM memories m
WHERE m.source = 'manual_save'
  AND ($1::text IS NULL OR m.owner_user_id = $1)
  AND m.content @@@ paradedb.parse($2)
ORDER BY paradedb.score(m.id) DESC
LIMIT $3
`

type Bm25SearchMemoriesParams struct {
	OwnerUserID *string
	QueryText   interface{}
	ResultLimit int32
}

type Bm25SearchMemoriesRow struct {
	ID        string
	Bm25Score float64
}

// BM25 full-text search over the memories table using ParadeDB's @@@ operator.
// Explicit casts ensure sqlc generates proper Go types.
// sqlc.narg(owner_user_id) enforces cross-tenant isolation.
func (q *Queries) Bm25SearchMemories(ctx context.Context, arg Bm25SearchMemoriesParams) ([]Bm25SearchMemoriesRow, error) {
	rows, err := q.db.Query(ctx, bm25SearchMemories, arg.OwnerUserID, arg.QueryText, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bm25SearchMemoriesRow
	for rows.Next() {
		var i Bm25SearchMemoriesRow
		if err := rows.Scan(&i.ID, &i.Bm25Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemoryEmbedding = `-- name: DeleteMemoryEmbedding :exec
DELETE FROM memory_embeddings WHERE memory_id = $1
`

func (q *Queries) DeleteMemoryEmbedding(ctx context.Context, memoryID string) error {
	_, err := q.db.Exec(ctx, deleteMemoryEmbedding, memoryID)
	return err
}

const hybridSearchMemories = `-- name: HybridSearchMemories :many
WITH
bm25_hits AS (
    SELECT m.id, paradedb.score(m.id)::float8 AS bm25_score
    FROM memories m
    WHERE m.source = 'manual_save'
      AND ($2::text IS NULL OR m.owner_user_id = $2)
      AND m.content @@@ paradedb.parse($3)
    ORDER BY paradedb.score(m.id) DESC
    LIMIT $1
),
vector_hits AS (
    SELECT me.memory_id AS id, (1.0 - (me.embedding <=> $4))::float8 AS vector_score
    FROM memory_embeddings me
    JOIN memories m ON me.memory_id = m.id
    WHERE me.embedding IS NOT NULL
      AND m.source = 'manual_save'
      AND ($2::text IS NULL OR m.owner_user_id = $2)
    ORDER BY me.embedding <=> $4
    LIMIT $1
)
SELECT
    COALESCE(b.id, v.id) AS id,
    (COALESCE(b.bm25_score, 0.0) * 0.4 + COALESCE(v.vector_score, 0.0) * 0.6)::float8 AS combined_score,
    COALESCE(b.bm25_score, 0.0)::float8 AS bm25_score,
    COALESCE(v.vector_score, 0.0)::float8 AS vector_score
FROM bm25_hits b
FULL OUTER JOIN vector_hits v ON b.id = v.id
ORDER BY combined_score DESC
LIMIT $1
`

type HybridSearchMemoriesParams struct {
	ResultLimit    int32
	OwnerUserID    *string
	QueryText      interface{}
	QueryEmbedding *pgvector.Vector
}

type HybridSearchMemoriesRow struct {
	ID            string
	CombinedScore float64
	Bm25Score     float64
	VectorScore   float64
}

// Full hybrid BM25 + vector search for memories using CTE-based approach.
// Combines BM25 and vector results with FULL OUTER JOIN.
// Weights: BM25 * 0.4 + vector * 0.6.
func (q *Queries) HybridSearchMemories(ctx context.Context, arg HybridSearchMemoriesParams) ([]HybridSearchMemoriesRow, error) {
	rows, err := q.db.Query(ctx, hybridSearchMemories,
		arg.ResultLimit,
		arg.OwnerUserID,
		arg.QueryText,
		arg.QueryEmbedding,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HybridSearchMemoriesRow
	for rows.Next() {
		var i HybridSearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CombinedScore,
			&i.Bm25Score,
			&i.VectorScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMemoryEmbedding = `-- name: InsertMemoryEmbedding :exec
INSERT INTO memory_embeddings (id, memory_id, embedding, model)
VALUES ($1, $2, $3, $4)
`

type InsertMemoryEmbeddingParams struct {
	ID        string
	MemoryID  string
	Embedding *pgvector.Vector
	Model     string
}

func (q *Queries) InsertMemoryEmbedding(ctx context.Context, arg InsertMemoryEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertMemoryEmbedding,
		arg.ID,
		arg.MemoryID,
		arg.Embedding,
		arg.Model,
	)
	return err
}

const vectorSearchMemories = `-- name: VectorSearchMemories :many
SELECT
    me.memory_id AS id,
    (1.0 - (me.embedding <=> $1))::float8 AS vector_score
FROM memory_embeddings me
JOIN memories m ON me.memory_id = m.id
WHERE me.embedding IS NOT NULL
  AND m.source = 'manual_save'
  AND ($2::text IS NULL OR m.owner_user_id = $2)
ORDER BY me.embedding <=> $1
LIMIT $3
`

type VectorSearchMemoriesParams struct {
	Embedding   *pgvector.Vector
	OwnerUserID *string
	Limit       int32
}

type VectorSearchMemoriesRow struct {
	ID          string
	VectorScore float64
}

// Cosine similarity search over memory embeddings using pgvector.
// Returns memory IDs with similarity scores (1 - cosine_distance).
// sqlc.narg(owner_user_id) enforces cross-tenant isolation.
func (q *Queries) VectorSearchMemories(ctx context.Context, arg VectorSearchMemoriesParams) ([]VectorSearchMemoriesRow, error) {
	rows, err := q.db.Query(ctx, vectorSearchMemories, arg.Embedding, arg.OwnerUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorSearchMemoriesRow
	for rows.Next() {
		var i VectorSearchMemoriesRow
		if err := rows.Scan(&i.ID, &i.VectorScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
