// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package store

import (
	"context"
)

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = $1
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMemory, id)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, owner_type, owner_user_id, owner_team_id, visibility, content, concepts, source, confidence, created_at, reflected FROM memories WHERE id = $1
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.Visibility,
		&i.Content,
		&i.Concepts,
		&i.Source,
		&i.Confidence,
		&i.CreatedAt,
		&i.Reflected,
	)
	return i, err
}

const insertMemory = `-- name: InsertMemory :one
INSERT INTO memories (id, owner_type, owner_user_id, owner_team_id, visibility, content, concepts, source, confidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_type, owner_user_id, owner_team_id, visibility, content, concepts, source, confidence, created_at, reflected
`

type InsertMemoryParams struct {
	ID          string
	OwnerType   string
	OwnerUserID *string
	OwnerTeamID *string
	Visibility  string
	Content     string
	Concepts    []string
	Source      string
	Confidence  float64
}

func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, insertMemory,
		arg.ID,
		arg.OwnerType,
		arg.OwnerUserID,
		arg.OwnerTeamID,
		arg.Visibility,
		arg.Content,
		arg.Concepts,
		arg.Source,
		arg.Confidence,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.Visibility,
		&i.Content,
		&i.Concepts,
		&i.Source,
		&i.Confidence,
		&i.CreatedAt,
		&i.Reflected,
	)
	return i, err
}

const listMemoriesByOwner = `-- name: ListMemoriesByOwner :many
SELECT id, owner_type, owner_user_id, owner_team_id, visibility, content, concepts, source, confidence, created_at, reflected FROM memories WHERE owner_user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListMemoriesByOwnerParams struct {
	OwnerUserID *string
	Limit       int32
}

func (q *Queries) ListMemoriesByOwner(ctx context.Context, arg ListMemoriesByOwnerParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByOwner, arg.OwnerUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.OwnerTeamID,
			&i.Visibility,
			&i.Content,
			&i.Concepts,
			&i.Source,
			&i.Confidence,
			&i.CreatedAt,
			&i.Reflected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVisibility = `-- name: UpdateVisibility :exec
UPDATE memories SET visibility = $2 WHERE id = $1
`

type UpdateVisibilityParams struct {
	ID         string
	Visibility string
}

func (q *Queries) UpdateVisibility(ctx context.Context, arg UpdateVisibilityParams) error {
	_, err := q.db.Exec(ctx, updateVisibility, arg.ID, arg.Visibility)
	return err
}
