// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories_ext.sql

package store

import (
	"context"
)

type BatchInsertMemoriesParams struct {
	ID          string
	OwnerType   string
	OwnerUserID *string
	OwnerTeamID *string
	Visibility  string
	Content     string
	Concepts    []string
	Source      string
	Confidence  float64
}

const listAllMemories = `-- name: ListAllMemories :many
SELECT id, owner_type, owner_user_id, owner_team_id, visibility, content, concepts, source, confidence, created_at, deleted, reflected FROM memories WHERE reflected = false AND deleted = false ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListAllMemories(ctx context.Context, limit int32) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listAllMemories, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.OwnerTeamID,
			&i.Visibility,
			&i.Content,
			&i.Concepts,
			&i.Source,
			&i.Confidence,
			&i.CreatedAt,
			&i.Deleted,
			&i.Reflected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
