// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package store

import (
	"context"
)

const checkSchemaMigrationsTableExists = `-- name: CheckSchemaMigrationsTableExists :one
SELECT EXISTS (
    SELECT FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'schema_migrations'
)
`

func (q *Queries) CheckSchemaMigrationsTableExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, checkSchemaMigrationsTableExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPgSearchExtension = `-- name: CreatePgSearchExtension :exec
CREATE EXTENSION IF NOT EXISTS pg_search
`

func (q *Queries) CreatePgSearchExtension(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createPgSearchExtension)
	return err
}

const createVectorExtension = `-- name: CreateVectorExtension :exec
CREATE EXTENSION IF NOT EXISTS vector
`

func (q *Queries) CreateVectorExtension(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createVectorExtension)
	return err
}

const getMigrationVersion = `-- name: GetMigrationVersion :one
SELECT version, dirty FROM schema_migrations LIMIT 1
`

func (q *Queries) GetMigrationVersion(ctx context.Context) (SchemaMigration, error) {
	row := q.db.QueryRow(ctx, getMigrationVersion)
	var i SchemaMigration
	err := row.Scan(&i.Version, &i.Dirty)
	return i, err
}

const listPublicTables = `-- name: ListPublicTables :many
SELECT table_name::text AS table_name FROM information_schema.tables
WHERE table_schema = 'public' ORDER BY table_name
`

func (q *Queries) ListPublicTables(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPublicTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var table_name string
		if err := rows.Scan(&table_name); err != nil {
			return nil, err
		}
		items = append(items, table_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
