// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string
	UserID     string
	Label      string
	KeyHash    string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type Session struct {
	ID        string
	UserID    string
	TeamID    *string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	Status    string
}

type Team struct {
	ID                string
	Name              string
	OwnerID           string
	DefaultVisibility string
	CreatedAt         pgtype.Timestamptz
}

type TeamMember struct {
	ID       string
	TeamID   string
	UserID   string
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	TotpSecret   *string
	TotpEnabled  bool
	CreatedAt    pgtype.Timestamptz
}
