// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ApiKey struct {
	ID         string
	UserID     string
	Label      string
	KeyHash    string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type CompressedEmbedding struct {
	CompressedID string
	Embedding    *pgvector.Vector
	Model        string
	CreatedAt    pgtype.Timestamptz
}

type CompressedObservation struct {
	ID             string
	ObservationIds []string
	SessionID      string
	OwnerType      string
	OwnerUserID    *string
	OwnerTeamID    *string
	Visibility     string
	CompressedText string
	Concepts       []string
	CreatedAt      pgtype.Timestamptz
}

type Crystal struct {
	ID         string
	ActionIds  []string
	Visibility string
	Narrative  string
	Files      []string
	Outcome    *string
	CreatedAt  pgtype.Timestamptz
}

type GraphEdge struct {
	ID         string
	FromNodeID string
	ToNodeID   string
	EdgeType   string
	Weight     float64
	CreatedAt  pgtype.Timestamptz
}

type GraphNode struct {
	ID        string
	NodeType  string
	EntityID  string
	Label     string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type Insight struct {
	ID                   string
	Title                string
	Content              string
	Confidence           float64
	ReinforcementCount   int32
	SourceConceptCluster []string
	SourceMemoryIds      []string
	SourceLessonIds      []string
	Project              *string
	Tags                 []string
	DecayRate            float64
	LastReinforcedAt     pgtype.Timestamptz
	LastDecayedAt        pgtype.Timestamptz
	Deleted              bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Lesson struct {
	ID               string
	TeamID           *string
	OwnerUserID      *string
	Visibility       string
	Content          string
	Context          *string
	Confidence       float64
	Source           string
	CreatedAt        pgtype.Timestamptz
	LastReinforcedAt pgtype.Timestamptz
}

type LessonReinforcement struct {
	ID              string
	LessonID        string
	ObservationID   *string
	ConfidenceDelta float64
	CreatedAt       pgtype.Timestamptz
}

type Memory struct {
	ID          string
	OwnerType   string
	OwnerUserID *string
	OwnerTeamID *string
	Visibility  string
	Content     string
	Concepts    []string
	Source      string
	Confidence  float64
	CreatedAt   pgtype.Timestamptz
	Reflected   bool
}

type Observation struct {
	ID           string
	SessionID    string
	OwnerType    string
	OwnerUserID  *string
	OwnerTeamID  *string
	Visibility   string
	Type         string
	Title        string
	Narrative    string
	Facts        *string
	Concepts     []string
	Files        []string
	Importance   float64
	Timestamp    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CompressedAt pgtype.Timestamptz
}

type ObservationEmbedding struct {
	ObservationID string
	Embedding     *pgvector.Vector
	Model         string
	CreatedAt     pgtype.Timestamptz
}

type ProceduralMemory struct {
	ID        string
	Content   string
	Trigger   *string
	CreatedAt pgtype.Timestamptz
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type Session struct {
	ID        string
	UserID    string
	TeamID    *string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	Status    string
}

type SessionSummary struct {
	ID          string
	SessionID   string
	OwnerType   string
	OwnerUserID *string
	OwnerTeamID *string
	Visibility  string
	SummaryText string
	Concepts    []string
	CreatedAt   pgtype.Timestamptz
	IsFull      bool
}

type Team struct {
	ID                string
	Name              string
	OwnerID           string
	DefaultVisibility string
	CreatedAt         pgtype.Timestamptz
}

type TeamMember struct {
	ID       string
	TeamID   string
	UserID   string
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	TotpSecret   *string
	TotpEnabled  bool
	CreatedAt    pgtype.Timestamptz
}
