// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteObservation = `-- name: DeleteObservation :exec
DELETE FROM observations WHERE id = $1
`

func (q *Queries) DeleteObservation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteObservation, id)
	return err
}

const getObservation = `-- name: GetObservation :one
SELECT id, session_id, owner_type, owner_user_id, owner_team_id, visibility, type, title, narrative, facts, concepts, files, importance, timestamp, created_at FROM observations WHERE id = $1
`

func (q *Queries) GetObservation(ctx context.Context, id string) (Observation, error) {
	row := q.db.QueryRow(ctx, getObservation, id)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.Visibility,
		&i.Type,
		&i.Title,
		&i.Narrative,
		&i.Facts,
		&i.Concepts,
		&i.Files,
		&i.Importance,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getObservationsByIDs = `-- name: GetObservationsByIDs :many
SELECT id, session_id, owner_type, owner_user_id, owner_team_id, visibility, type, title, narrative, facts, concepts, files, importance, timestamp, created_at FROM observations WHERE id = ANY($1::text[])
`

func (q *Queries) GetObservationsByIDs(ctx context.Context, dollar_1 []string) ([]Observation, error) {
	rows, err := q.db.Query(ctx, getObservationsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.OwnerTeamID,
			&i.Visibility,
			&i.Type,
			&i.Title,
			&i.Narrative,
			&i.Facts,
			&i.Concepts,
			&i.Files,
			&i.Importance,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertObservation = `-- name: InsertObservation :one
INSERT INTO observations (id, session_id, owner_type, owner_user_id, owner_team_id, visibility, type, title, narrative, facts, concepts, files, importance, timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, session_id, owner_type, owner_user_id, owner_team_id, visibility, type, title, narrative, facts, concepts, files, importance, timestamp, created_at
`

type InsertObservationParams struct {
	ID          string
	SessionID   string
	OwnerType   string
	OwnerUserID *string
	OwnerTeamID *string
	Visibility  string
	Type        string
	Title       string
	Narrative   string
	Facts       *string
	Concepts    []string
	Files       []string
	Importance  float64
	Timestamp   pgtype.Timestamptz
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, insertObservation,
		arg.ID,
		arg.SessionID,
		arg.OwnerType,
		arg.OwnerUserID,
		arg.OwnerTeamID,
		arg.Visibility,
		arg.Type,
		arg.Title,
		arg.Narrative,
		arg.Facts,
		arg.Concepts,
		arg.Files,
		arg.Importance,
		arg.Timestamp,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OwnerType,
		&i.OwnerUserID,
		&i.OwnerTeamID,
		&i.Visibility,
		&i.Type,
		&i.Title,
		&i.Narrative,
		&i.Facts,
		&i.Concepts,
		&i.Files,
		&i.Importance,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const listObservationsBySession = `-- name: ListObservationsBySession :many
SELECT id, session_id, owner_type, owner_user_id, owner_team_id, visibility, type, title, narrative, facts, concepts, files, importance, timestamp, created_at FROM observations WHERE session_id = $1 ORDER BY timestamp LIMIT $2
`

type ListObservationsBySessionParams struct {
	SessionID string
	Limit     int32
}

func (q *Queries) ListObservationsBySession(ctx context.Context, arg ListObservationsBySessionParams) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.OwnerTeamID,
			&i.Visibility,
			&i.Type,
			&i.Title,
			&i.Narrative,
			&i.Facts,
			&i.Concepts,
			&i.Files,
			&i.Importance,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByUserID = `-- name: ListObservationsByUserID :many
SELECT o.id, o.session_id, o.owner_type, o.owner_user_id, o.owner_team_id, o.visibility, o.type, o.title, o.narrative, o.facts, o.concepts, o.files, o.importance, o.timestamp, o.created_at FROM observations o
JOIN sessions s ON o.session_id = s.id
WHERE s.user_id = $1
ORDER BY o.created_at DESC
LIMIT $2
`

type ListObservationsByUserIDParams struct {
	UserID string
	Limit  int32
}

func (q *Queries) ListObservationsByUserID(ctx context.Context, arg ListObservationsByUserIDParams) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listObservationsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.OwnerTeamID,
			&i.Visibility,
			&i.Type,
			&i.Title,
			&i.Narrative,
			&i.Facts,
			&i.Concepts,
			&i.Files,
			&i.Importance,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentObservations = `-- name: ListRecentObservations :many
SELECT id, session_id, owner_type, owner_user_id, owner_team_id, visibility, type, title, narrative, facts, concepts, files, importance, timestamp, created_at FROM observations ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentObservations(ctx context.Context, limit int32) ([]Observation, error) {
	rows, err := q.db.Query(ctx, listRecentObservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OwnerType,
			&i.OwnerUserID,
			&i.OwnerTeamID,
			&i.Visibility,
			&i.Type,
			&i.Title,
			&i.Narrative,
			&i.Facts,
			&i.Concepts,
			&i.Files,
			&i.Importance,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
