// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations_ext.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConceptFrequencies = `-- name: GetConceptFrequencies :many
SELECT unnest(concepts) AS concept, count(*) AS freq
FROM observations
WHERE concepts IS NOT NULL AND cardinality(concepts) > 0
GROUP BY concept
ORDER BY freq DESC
LIMIT 50
`

type GetConceptFrequenciesRow struct {
	Concept interface{}
	Freq    int64
}

func (q *Queries) GetConceptFrequencies(ctx context.Context) ([]GetConceptFrequenciesRow, error) {
	rows, err := q.db.Query(ctx, getConceptFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConceptFrequenciesRow
	for rows.Next() {
		var i GetConceptFrequenciesRow
		if err := rows.Scan(&i.Concept, &i.Freq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileHistory = `-- name: GetFileHistory :many
SELECT id, session_id, title, narrative, files, timestamp
FROM observations
WHERE files IS NOT NULL AND files && $1
  AND session_id != $2
ORDER BY timestamp DESC
LIMIT 100
`

type GetFileHistoryParams struct {
	Files     []string
	SessionID string
}

type GetFileHistoryRow struct {
	ID        string
	SessionID string
	Title     string
	Narrative string
	Files     []string
	Timestamp pgtype.Timestamptz
}

func (q *Queries) GetFileHistory(ctx context.Context, arg GetFileHistoryParams) ([]GetFileHistoryRow, error) {
	rows, err := q.db.Query(ctx, getFileHistory, arg.Files, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFileHistoryRow
	for rows.Next() {
		var i GetFileHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Title,
			&i.Narrative,
			&i.Files,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvictionCandidates = `-- name: ListEvictionCandidates :many
SELECT id, importance,
       EXTRACT(EPOCH FROM (now() - created_at)) / 86400 AS age_days
FROM observations
WHERE importance < $1
ORDER BY importance ASC, created_at ASC
LIMIT $2
`

type ListEvictionCandidatesParams struct {
	Importance float64
	Limit      int32
}

type ListEvictionCandidatesRow struct {
	ID         string
	Importance float64
	AgeDays    int32
}

func (q *Queries) ListEvictionCandidates(ctx context.Context, arg ListEvictionCandidatesParams) ([]ListEvictionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listEvictionCandidates, arg.Importance, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvictionCandidatesRow
	for rows.Next() {
		var i ListEvictionCandidatesRow
		if err := rows.Scan(&i.ID, &i.Importance, &i.AgeDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
