// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package store

import (
	"context"
)

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM project_profiles WHERE project_slug = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, projectSlug string) error {
	_, err := q.db.Exec(ctx, deleteProfile, projectSlug)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT project_slug, top_concepts, top_files, conventions, common_errors, created_at, updated_at FROM project_profiles WHERE project_slug = $1
`

func (q *Queries) GetProfile(ctx context.Context, projectSlug string) (ProjectProfile, error) {
	row := q.db.QueryRow(ctx, getProfile, projectSlug)
	var i ProjectProfile
	err := row.Scan(
		&i.ProjectSlug,
		&i.TopConcepts,
		&i.TopFiles,
		&i.Conventions,
		&i.CommonErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO project_profiles (project_slug, top_concepts, top_files, conventions, common_errors)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_slug) DO UPDATE SET
    top_concepts = EXCLUDED.top_concepts,
    top_files = EXCLUDED.top_files,
    conventions = EXCLUDED.conventions,
    common_errors = EXCLUDED.common_errors,
    updated_at = now()
`

type UpsertProfileParams struct {
	ProjectSlug  string
	TopConcepts  []byte
	TopFiles     []byte
	Conventions  []string
	CommonErrors []byte
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.ProjectSlug,
		arg.TopConcepts,
		arg.TopFiles,
		arg.Conventions,
		arg.CommonErrors,
	)
	return err
}
