// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler_queries.sql

package store

import (
	"context"
)

const claimUncompressedObservations = `-- name: ClaimUncompressedObservations :many
SELECT id, title, narrative, facts, concepts, session_id
FROM observations
WHERE session_id = $1 AND compressed_at IS NULL
ORDER BY created_at
FOR UPDATE SKIP LOCKED
`

type ClaimUncompressedObservationsRow struct {
	ID        string
	Title     string
	Narrative string
	Facts     *string
	Concepts  []string
	SessionID string
}

func (q *Queries) ClaimUncompressedObservations(ctx context.Context, sessionID string) ([]ClaimUncompressedObservationsRow, error) {
	rows, err := q.db.Query(ctx, claimUncompressedObservations, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimUncompressedObservationsRow
	for rows.Next() {
		var i ClaimUncompressedObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Narrative,
			&i.Facts,
			&i.Concepts,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUnreflectedMemories = `-- name: HasUnreflectedMemories :one
SELECT COUNT(*) > 0 AS has_unreflected FROM memories m
WHERE NOT EXISTS (
    SELECT 1 FROM insights i
    WHERE i.source = 'reflect' AND i.created_at > m.created_at
)
`

func (q *Queries) HasUnreflectedMemories(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnreflectedMemories)
	var has_unreflected bool
	err := row.Scan(&has_unreflected)
	return has_unreflected, err
}

const listSessionsNeedingSummarization = `-- name: ListSessionsNeedingSummarization :many
SELECT s.id FROM sessions s
JOIN observations o ON o.session_id = s.id
LEFT JOIN session_summaries ss ON ss.session_id = s.id
WHERE o.compressed_at IS NOT NULL
  AND (ss.created_at IS NULL OR o.compressed_at > ss.created_at)
GROUP BY s.id, ss.created_at
`

func (q *Queries) ListSessionsNeedingSummarization(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSessionsNeedingSummarization)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsWithUncompressedObservations = `-- name: ListSessionsWithUncompressedObservations :many
SELECT DISTINCT session_id FROM observations
WHERE compressed_at IS NULL AND session_id IS NOT NULL
ORDER BY session_id
`

func (q *Queries) ListSessionsWithUncompressedObservations(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSessionsWithUncompressedObservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconsolidatedSessions = `-- name: ListUnconsolidatedSessions :many
SELECT ss.session_id FROM session_summaries ss
WHERE NOT EXISTS (
    SELECT 1 FROM memories m
    WHERE m.source = 'consolidation' AND m.created_at > ss.created_at
)
`

func (q *Queries) ListUnconsolidatedSessions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnconsolidatedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
