// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const bm25Search = `-- name: Bm25Search :many
SELECT s.id::text AS id, s.bm25_score::float8 AS bm25_score
FROM bm25_search($1, $2, $3) s
`

type Bm25SearchParams struct {
	QueryText   string
	ResultLimit int32
	OwnerUserID string
}

type Bm25SearchRow struct {
	ID        string
	Bm25Score float64
}

// BM25 full-text search via the bm25_search wrapper function.
// Explicit casts ensure sqlc generates proper Go types.
// $3 (owner_user_id) enforces cross-tenant isolation.
func (q *Queries) Bm25Search(ctx context.Context, arg Bm25SearchParams) ([]Bm25SearchRow, error) {
	rows, err := q.db.Query(ctx, bm25Search, arg.QueryText, arg.ResultLimit, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bm25SearchRow
	for rows.Next() {
		var i Bm25SearchRow
		if err := rows.Scan(&i.ID, &i.Bm25Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const graphTraversal = `-- name: GraphTraversal :many
WITH RECURSIVE graph_traversal AS (
    SELECT
        gn.id AS node_id,
        gn.entity_id AS observation_id,
        0 AS depth,
        0.0::float AS graph_score
    FROM graph_nodes gn
    WHERE gn.entity_id = ANY($1::text[])

    UNION ALL

    SELECT
        gn.id,
        gn.entity_id,
        gt.depth + 1,
        gt.graph_score + ge.weight
    FROM graph_nodes gn
    JOIN graph_edges ge ON gn.id = ge.to_node_id
    JOIN graph_traversal gt ON ge.from_node_id = gt.node_id
    WHERE gt.depth < 2
)
SELECT DISTINCT observation_id AS id, MAX(graph_score)::float8 AS graph_score
FROM graph_traversal
WHERE observation_id IS NOT NULL
  AND observation_id != ALL($1::text[])
GROUP BY observation_id
`

type GraphTraversalRow struct {
	ID         string
	GraphScore float64
}

// Recursive graph traversal from seed observation IDs.
// Expands up to 2 hops through graph_edges, accumulating edge weights.
// Returns observation IDs discovered via graph with traversal scores.
func (q *Queries) GraphTraversal(ctx context.Context, dollar_1 []string) ([]GraphTraversalRow, error) {
	rows, err := q.db.Query(ctx, graphTraversal, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphTraversalRow
	for rows.Next() {
		var i GraphTraversalRow
		if err := rows.Scan(&i.ID, &i.GraphScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hybridSearch = `-- name: HybridSearch :many
SELECT
    s.id::text AS id,
    s.combined_score::float8 AS combined_score,
    s.bm25_score::float8 AS bm25_score,
    s.vector_score::float8 AS vector_score
FROM hybrid_search($1, $2, $3, $4) s
`

type HybridSearchParams struct {
	QueryText      string
	QueryEmbedding *pgvector.Vector
	ResultLimit    int32
	OwnerUserID    string
}

type HybridSearchRow struct {
	ID            string
	CombinedScore float64
	Bm25Score     float64
	VectorScore   float64
}

// Full hybrid BM25 + vector search via the hybrid_search wrapper function.
// Combines both streams with FULL OUTER JOIN.
// Weights: BM25 * 0.4 + vector * 0.6.
// $4 (owner_user_id) enforces cross-tenant isolation.
func (q *Queries) HybridSearch(ctx context.Context, arg HybridSearchParams) ([]HybridSearchRow, error) {
	rows, err := q.db.Query(ctx, hybridSearch,
		arg.QueryText,
		arg.QueryEmbedding,
		arg.ResultLimit,
		arg.OwnerUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HybridSearchRow
	for rows.Next() {
		var i HybridSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.CombinedScore,
			&i.Bm25Score,
			&i.VectorScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vectorSearch = `-- name: VectorSearch :many
SELECT
    oe.observation_id AS id,
    (1.0 - (oe.embedding <=> $1))::float8 AS vector_score
FROM observation_embeddings oe
WHERE oe.embedding IS NOT NULL
ORDER BY oe.embedding <=> $1
LIMIT $2
`

type VectorSearchParams struct {
	Embedding *pgvector.Vector
	Limit     int32
}

type VectorSearchRow struct {
	ID          string
	VectorScore float64
}

// Cosine similarity search over observation embeddings using pgvector.
// Returns observation IDs with similarity scores (1 - cosine_distance).
func (q *Queries) VectorSearch(ctx context.Context, arg VectorSearchParams) ([]VectorSearchRow, error) {
	rows, err := q.db.Query(ctx, vectorSearch, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorSearchRow
	for rows.Next() {
		var i VectorSearchRow
		if err := rows.Scan(&i.ID, &i.VectorScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
