// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, team_id, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, user_id, team_id, started_at, ended_at, status
`

type CreateSessionParams struct {
	ID     string
	UserID string
	TeamID *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID, arg.TeamID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE sessions SET ended_at = now(), status = 'ended' WHERE id = $1 RETURNING id, user_id, team_id, started_at, ended_at, status
`

func (q *Queries) EndSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, team_id, started_at, ended_at, status FROM sessions WHERE user_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveSession(ctx context.Context, userID string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, team_id, started_at, ended_at, status FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, team_id, started_at, ended_at, status FROM sessions WHERE user_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListSessionsByUserParams struct {
	UserID string
	Limit  int32
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
