// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package store

import (
	"context"
)

const getSessionSummary = `-- name: GetSessionSummary :one
SELECT id, session_id, visibility, summary_text, concepts, created_at FROM session_summaries WHERE session_id = $1
`

func (q *Queries) GetSessionSummary(ctx context.Context, sessionID string) (SessionSummary, error) {
	row := q.db.QueryRow(ctx, getSessionSummary, sessionID)
	var i SessionSummary
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Visibility,
		&i.SummaryText,
		&i.Concepts,
		&i.CreatedAt,
	)
	return i, err
}

const listSummariesBySession = `-- name: ListSummariesBySession :many
SELECT id, session_id, visibility, summary_text, concepts, created_at FROM session_summaries WHERE session_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSummariesBySession(ctx context.Context, sessionID string) ([]SessionSummary, error) {
	rows, err := q.db.Query(ctx, listSummariesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSummary
	for rows.Next() {
		var i SessionSummary
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Visibility,
			&i.SummaryText,
			&i.Concepts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSessionSummary = `-- name: UpsertSessionSummary :one
INSERT INTO session_summaries (id, session_id, visibility, summary_text, concepts)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id) DO UPDATE SET
    summary_text = EXCLUDED.summary_text,
    concepts = EXCLUDED.concepts,
    visibility = EXCLUDED.visibility
RETURNING id, session_id, visibility, summary_text, concepts, created_at
`

type UpsertSessionSummaryParams struct {
	ID          string
	SessionID   string
	Visibility  string
	SummaryText string
	Concepts    []string
}

func (q *Queries) UpsertSessionSummary(ctx context.Context, arg UpsertSessionSummaryParams) (SessionSummary, error) {
	row := q.db.QueryRow(ctx, upsertSessionSummary,
		arg.ID,
		arg.SessionID,
		arg.Visibility,
		arg.SummaryText,
		arg.Concepts,
	)
	var i SessionSummary
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Visibility,
		&i.SummaryText,
		&i.Concepts,
		&i.CreatedAt,
	)
	return i, err
}
