// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package store

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, owner_id, default_visibility)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner_id, default_visibility, created_at
`

type CreateTeamParams struct {
	ID                string
	Name              string
	OwnerID           string
	DefaultVisibility string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.DefaultVisibility,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.DefaultVisibility,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, owner_id, default_visibility, created_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.DefaultVisibility,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamsByOwner = `-- name: ListTeamsByOwner :many
SELECT id, name, owner_id, default_visibility, created_at FROM teams WHERE owner_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListTeamsByOwnerParams struct {
	OwnerID string
	Limit   int32
}

func (q *Queries) ListTeamsByOwner(ctx context.Context, arg ListTeamsByOwnerParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.DefaultVisibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET name = $2, default_visibility = $3
WHERE id = $1
RETURNING id, name, owner_id, default_visibility, created_at
`

type UpdateTeamParams struct {
	ID                string
	Name              string
	DefaultVisibility string
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.Name, arg.DefaultVisibility)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.DefaultVisibility,
		&i.CreatedAt,
	)
	return i, err
}
