// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_members.sql

package store

import (
	"context"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (id, team_id, user_id)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, joined_at
`

type AddTeamMemberParams struct {
	ID     string
	TeamID string
	UserID string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.ID, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.JoinedAt,
	)
	return i, err
}

const getUserTeam = `-- name: GetUserTeam :one
SELECT t.id, t.name, t.owner_id, t.default_visibility, t.created_at FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserTeam(ctx context.Context, userID string) (Team, error) {
	row := q.db.QueryRow(ctx, getUserTeam, userID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.DefaultVisibility,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT id, team_id, user_id, joined_at FROM team_members WHERE team_id = $1 ORDER BY joined_at
`

func (q *Queries) ListTeamMembers(ctx context.Context, teamID string) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID string
	UserID string
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}
